# Generated by Django 2.2.7 on 2020-08-23 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0013_northapost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LPost',
            new_name='CenterPost',
        ),
        migrations.RenameModel(
            old_name='RPost',
            new_name='LeftPost',
        ),
        migrations.RenameModel(
            old_name='CPost',
            new_name='RightPost',
        ),
    ]
