# Generated by Django 2.2.7 on 2020-08-23 03:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0014_auto_20200823_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NorthAPost',
            new_name='NorthAmericaPost',
        ),
    ]
