# Generated by Django 2.2.7 on 2020-08-23 03:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0015_auto_20200823_0838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiniCPost',
            new_name='MiniCenterPost',
        ),
    ]
